### ISSUE TITLE
WMctrl is not a needed dependency

### ISSUE THREAD

**Issue by ar1ja** [yrwq/yafetch#8]
WMctrl doesn't seem like a dependency, I don't have it and it seems fine, not sure why that would be a dependency, can you enlighten me on why you'd need that?

**Comment by ar1ja** [comment]
Seems like a dependency of [an old commit](https://github.com/yrwq/yafetch/commit/6fccbe7285119a2684ba32354b4947621c902c69), but I can't see it being in the current code

**Comment by yrwq** [comment]
It will be a dependency as soon as i finish a function that requires it.

**Comment by ar1ja** [comment]
> It will be a dependency as soon as i finish a function that requires it.

ag, sorry
